spring:
  profiles:
    active: cloud
    
---
spring:
  profiles: docker
  rabbitmq:
    username: guest
    password: guest
    host: rabbitmq

server:
  port: 1111
  

    
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
  instance:
    preferIpAddress: true