server:
  port: 2222
  
spring:
  profiles: docker
  rabbitmq:
    username: guest
    password: guest
    host: rabbitmq

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5
  instance:
    preferIpAddress: true