server:
  port: 8765

spring:
  profiles: docker
    
eureka:
  instance:
    hostname: zuul
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/

zuul:
  routes:
    student:
      path: /student/**
      url: http://student:1111
    teacher:
      path: /teacher/**
      url: http://teacher:2222
      
management:
  security:
    enabled: false