spring:
  application:
    name: zuul
    

server:
  port: 8765
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:{server.port}:${random.value}}

zuul:
  routes:
    student:
      path: /student/**
      serviceId: STUDENT  
    teacher:
      path: /teacher/**
      serviceId: TEACHER
      
---
server:
  port: 8765

spring:
  profiles: docker
    
eureka:
  instance:
    hostname: zuul
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/

zuul:
  routes:
    student:
      path: /student/**
      url: http://student:1111
    teacher:
      path: /teacher/**
      url: http://teacher:2222

management:
  security:
    enabled: false